dist: xenial
language: python
python:
  - "3.7"

# add docker capabilities to travis build
services:
  - docker

# build a and run the docker image
before_install:
  - docker build -t ideahub:latest .
  - docker run --detach --name ideahub -p 5000:5000 ideahub:latest

# install python dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

# command to run tests
script:
  - coverage run --source=app -m unittest discover -s test -p "*_tests.py" -v

# Push the results to codecov
after_success:
  - codecov