from flask_restplus import fields

from app.apis.namespaces import vote_ns

vote = vote_ns.model('Vote', {
    'id': fields.Integer(readOnly=True, description='The vote\'s autogenerated id'),
    'owner': fields.Integer(readOnly=True, required=True, description='The id of the user that issued the vote'),
    'target': fields.Integer(readOnly=True, required=True, description='The id of the idea that the vote belongs to'),
    'value': fields.Integer(readOnly=True, description='The value of the vote'),
    'created': fields.DateTime(readOnly=True, description='The vote\'s creation date'),
    'modified': fields.DateTime(readOnly=True, description='The vote\'s last modified date')
})

new_vote = vote_ns.model('New Vote', {
    'target': fields.Integer(readOnly=True, required=True, description='The idea id that the vote belongs to'),
    'value': fields.Integer(readOnly=True, required=True, description='The value of the vote')
})

modify_vote = vote_ns.model('Modify Vote', {
    'value': fields.Integer(readOnly=True, required=True, description='The value of the vote')
})
